// 除外するディレクトリ名(※名前に完全一致)
// TODO: ちゃんとする
exclude_dirs = [
    ".git",
    ".nuxt",
    ".vscode",
    ".vs",
    "Debug",
    "dist",
    "ipch",
    "node_modules",
    "Release",
    "target",
    "x64",
]

// 除外するファイル名(※名前に対して部分一致)
// TODO: ちゃんとする
exclude_files = [
    ".ipch",
    ".VC.db",
    ".vcxproj.user",
    ".zip",
]
